### ISSUE TITLE
Run frontend project was not successfully

### ISSUE THREAD

**Issue by SamerPTUK** [0xpolarzero/chainlink-functions-next-starter#1]
Hello dear
Thanks for your project
I tried to run frontend project using yarn dev command as descried in readme file:
Output:

yarn run v1.22.19
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from C:\Users\Dell\Downloads\chainlink-functions-next-starter\frontend\.env
warn  - You have enabled experimental feature (appDir) in next.config.js.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

event - compiled client and server successfully in 4.3s (263 modules)
wait  - compiling...
event - compiled client and server successfully in 1087 ms (263 modules)
wait  - compiling /page (client and server)...
warn  - ./node_modules/eccrypto/index.js
Module not found: Can't resolve './build/Release/ecdh' in 'C:\Users\Dell\Downloads\chainlink-functions-next-starter\frontend\node_modules\eccrypto'

Import trace for requested module:
./node_modules/eccrypto/index.js
./node_modules/eth-crypto/dist/lib/decrypt-with-private-key.js
./node_modules/eth-crypto/dist/lib/index.js
./app/systems/request/FunctionsSandboxLibrary/encryptSecrets.js
./app/systems/request/FunctionsSandboxLibrary/buildRequest.js
./app/systems/request/FunctionsSandboxLibrary/index.js
./app/systems/request/request.js
./app/components/Main/Request.jsx
./app/components/Main/Main.jsx
./app/components/Main/index.js
./app/page.js
error - SyntaxError: Illegal return statement
    at __webpack_require__ (C:\Users\Dell\Downloads\chainlink-functions-next-starter\frontend\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\Dell\Downloads\chainlink-functions-next-starter\frontend\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\Dell\Downloads\chainlink-functions-next-starter\frontend\.next\server\webpack-runtime.js:33:43)
    at eval (./app/systems/request/FunctionsSandboxLibrary/encryptSecrets.js:11:38)
    at (sc_client)/./app/systems/request/FunctionsSandboxLibrary/encryptSecrets.js (C:\Users\Dell\Downloads\chainlink-functions-next-starter\frontend\.next\server\app\page.js:3565:1)
    at __webpack_require__ (C:\Users\Dell\Downloads\chainlink-functions-next-starter\frontend\.next\server\webpack-runtime.js:33:43)
    at eval (./app/systems/request/FunctionsSandboxLibrary/buildRequest.js:7:26)
    at (sc_client)/./app/systems/request/FunctionsSandboxLibrary/buildRequest.js (C:\Users\Dell\Downloads\chainlink-functions-next-starter\frontend\.next\server\app\page.js:3554:1)
    at __webpack_require__ (C:\Users\Dell\Downloads\chainlink-functions-next-starter\frontend\.next\server\webpack-runtime.js:33:43)
    at eval (./app/systems/request/FunctionsSandboxLibrary/index.js:7:22)
    at (sc_client)/./app/systems/request/FunctionsSandboxLibrary/index.js (C:\Users\Dell\Downloads\chainlink-functions-next-starter\frontend\.next\server\app\page.js:3587:1)
    at __webpack_require__ (C:\Users\Dell\Downloads\chainlink-functions-next-starter\frontend\.next\server\webpack-runtime.js:33:43)
    at eval (./app/systems/request/request.js:3:27)
    at (sc_client)/./app/systems/request/request.js (C:\Users\Dell\Downloads\chainlink-functions-next-starter\frontend\.next\server\app\page.js:3609:1)
    at __webpack_require__ (C:\Users\Dell\Downloads\chainlink-functions-next-starter\frontend\.next\server\webpack-runtime.js:33:43)
    at eval (./app/components/Main/Request.jsx:10:89)
    at (sc_client)/./app/components/Main/Request.jsx (C:\Users\Dell\Downloads\chainlink-functions-next-starter\frontend\.next\server\app\page.js:3477:1)
    at __webpack_require__ (C:\Users\Dell\Downloads\chainlink-functions-next-starter\frontend\.next\server\webpack-runtime.js:33:43)
    at eval (./app/components/Main/Main.jsx:8:66)
    at (sc_client)/./app/components/Main/Main.jsx (C:\Users\Dell\Downloads\chainlink-functions-next-starter\frontend\.next\server\app\page.js:3466:1)
    at __webpack_require__ (C:\Users\Dell\Downloads\chainlink-functions-next-starter\frontend\.next\server\webpack-runtime.js:33:43)
    at eval (./app/components/Main/index.js:5:63)
    at (sc_client)/./app/components/Main/index.js (C:\Users\Dell\Downloads\chainlink-functions-next-starter\frontend\.next\server\app\page.js:3488:1)
    at __webpack_require__ (C:\Users\Dell\Downloads\chainlink-functions-next-starter\frontend\.next\server\webpack-runtime.js:33:43)
    at eval (./app/page.js:11:74)
    at (sc_client)/./app/page.js (C:\Users\Dell\Downloads\chainlink-functions-next-starter\frontend\.next\server\app\page.js:3499:1)
    at __webpack_require__ (C:\Users\Dell\Downloads\chainlink-functions-next-starter\frontend\.next\server\webpack-runtime.js:33:43)

Page http://localhost:3000/ appear and after click on (Perform Request) get Request Failed This subscription might be out of LINK.

Please your help

**Comment by Isoltec** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!
